services:
  mongodb:
    image: postgres:14.3
    container_name: reservations_pg
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: reservations
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    networks:
      - reservations-network

volumes:
  reservations-db:
    driver: local

networks:
  reservations-network:
    driver: bridge
